from django.db import models
from uuid import uuid4

# Create your models here.
class Books(models.Model):
    id_book = models.UUIDField(primary_key=True,default=uuid4, editable=False)
    title = models.CharField(max_length=255)
    author = models.CharField(max_length=255)
    release_year = models.IntegerField()
    state = models.CharField(max_length=50)
    pages = models.IntegerField()
    publishing_company = models.CharField(max_length=255)
    create_at = models.DateField(auto_now_add=True)


class Empresa(models.Model):
    EMP_ID   =            models.UUIDField(primary_key=True,default=uuid4, editable=False)
    EMP_FANTASIA =         models.CharField(max_length=255)
    EMP_RAZAOSOCIAL  =     models.CharField(max_length=255)
    EMP_NOMEREDUZIDO   =   models.CharField(max_length=255)
    EMP_PESSOA    =        models.CharField(max_length=1)
    EMP_CPF      =         models.CharField(max_length=11)
    EMP_CNPJ     =         models.CharField(max_length=18)
    EMP_FONES       =       models.CharField(max_length=50)
    EMP_CONTATO     =       models.CharField(max_length=50)
    EMP_SITUACAO    =       models.CharField(max_length=1)
    EMP_OBSERVACAO   =      models.CharField(max_length=255)
    EMP_USUCAD     =        models.CharField(max_length=15)
    EMP_DATCAD     =        models.DateTimeField()
    EMP_USUMOD     =       models.CharField(max_length=15)
    EMP_DATMOD     =       models.DateTimeField()
    EMP_ATIVA       =       models.CharField(max_length=1)
    EMP_API_GOOGLE   =      models.CharField(max_length=255)
    EM_API_URL_BASE   =     models.CharField(max_length=255)
    EMP_API_PAGSEGURO   =  models.CharField(max_length=255)
    EMP_API_URL_BASE    =  models.CharField(max_length=255)
    EMP_VR_KM       =      models.FloatField()
    LIMITE_FIXO    =       models.IntegerField()
    STATUS         =       models.IntegerField()
    VR_LIMITE_FIXO   =       models.FloatField()
    EM_CEP          =      models.CharField(max_length=255)
    EMP_ENDERECO    =      models.CharField(max_length=255),
    EMP_BAIRRO      =      models.CharField(max_length=255)
    EMP_COMPLEMENTO   =     models.CharField(max_length=255)
    EMP_EMAIL         =    models.CharField(max_length=255)
    EMP_NUMERO    =         models.IntegerField()
    EMP_UF            =     models.CharField(max_length=2)
    EMP_CIDADE         =   models.CharField(max_length=255)
    EMP_TELEFONE        =   models.CharField(max_length=255)
    EMP_CELULAR         =   models.CharField(max_length=255)
    EMP_DT_FUNDACAO     =   models.DateField()
    EMP_INC_MUNICIPAL   =   models.CharField(max_length=255)
    EMP_INC_ESTADUAL   =   models.CharField(max_length=255)
    API_KEY_G          =   models.CharField(max_length=255)
    API_CNPJ           =   models.CharField(max_length=255)
    API_CEP            =   models.CharField(max_length=255)
    CHAVE_PIX          =   models.CharField(max_length=255)
    API_WATS               =models.CharField(max_length=255)
    API_WATS_BASE          =models.CharField(max_length=255)
    DIA_DE_FECHAMENTO =   models.IntegerField()
    INICIO_ATIVIDADES     = models.TimeField()
    FIM_ATIVIDADES    =    models.TimeField()
    URLGOOGLE         =    models.CharField(max_length=255)
    COD_PROJ_GOOGLE   =     models.CharField(max_length=255)
    API_GOOGLE         =    models.CharField(max_length=255)
    IMPRIMIR        =       models.IntegerField()
    IP_IMPRESSORA_TERMICA  = models.CharField(max_length=255)
    NM_IMPRESSORA          = models.CharField(max_length=255)

class Entregas(models.Model):   
    ID                  =        models.UUIDField(primary_key=True,default=uuid4, editable=False)
    ID_TIPO_PRODUTO      =      models.IntegerField(default=3)
    ID_PESSOA           =      models.IntegerField(default=0)
    ID_MOTOQUEIRO       =      models.IntegerField(default=0)
    DT_CADASTRO         =     models.DateTimeField(auto_now_add=True)
    DT_SAIDA           =        models.DateField()
    DT_ENTREGA          =     models.DateTimeField(auto_now_add=True)
    ENDERECO_RETIRADA          = models.CharField(max_length=600)
    ENDERECO_ENTREGA            = models.CharField(max_length=600)
    DESCRICAO                  = models.CharField(max_length=600)
    DISTANCIA            =       models.IntegerField()
    DISTANCIA_TXT               = models.CharField(max_length=30)
    VR_CALCULADO       =          models.FloatField()
    VR_POR_METRO      =           models.FloatField()
    STATUS                      = models.CharField(max_length=1)
    ID_FORMA_PGTO        =       models.IntegerField()
    ID_EMPRESA           =       models.IntegerField()
    ID_USUARIO_ENCERRAMENTO   =       models.IntegerField()
    ID_USUARIO_INCLUSAO       =       models.IntegerField()
    COD_TRANSACAO              = models.CharField(max_length=20)
    BAIRRO_ENTREGA              = models.CharField(max_length=255)
    TRANSACAO_GUID              = models.CharField(max_length=38)
    ENDERECO_CLIENTE            = models.CharField(max_length=600)
    ANOTACAO                    = models.CharField(max_length=600)
    ID_USUARIO_ENCAMINHAMENTO  =       models.IntegerField(default=0)
    TRANSFERIDO                 =       models.IntegerField(default=0)

class Clientes(models.Model): 
    IDPESSOA           =        models.UUIDField(primary_key=True,default=uuid4, editable=False)
    NOME                = models.CharField(max_length=255)
    EMAIL               = models.CharField(max_length=255)
    CPF                 = models.CharField(max_length=20)
    CELULAR             = models.CharField(max_length=20)
    LATITUDE            = models.CharField(max_length=20)
    LONGITUDE           = models.CharField(max_length=20)
    ONLINE           =    models.IntegerField(default=0)
    TOKEN               = models.CharField(max_length=255)
    SENHA                = models.CharField(max_length=10)
    STATUS               = models.CharField(max_length=1)
    TP_PESSOA            = models.CharField(max_length=1, default="C")
    DT_TIME_ONLINE     =     models.DateTimeField(auto_now_add=True)
    ENDERECO             = models.CharField(max_length=100)
    BAIRRO               = models.CharField(max_length=100)
    NUMERO           =   models.IntegerField(default=0)
    COMPLEMENTO          = models.CharField(max_length=100)
    CEP                = models.CharField(max_length=9)
    ESTADO             = models.CharField(max_length=100)
    CIDADE             = models.CharField(max_length=100)
    TP_CPF_CNPJ     =    models.IntegerField(default=0)
    TEM_CONTRATO     =    models.IntegerField(default=0)
    ID_EMPRESA        =   models.IntegerField(default=0)
    ID_USUARIO        =   models.IntegerField(default=0)
    IDMOTOQUEIRO      =  models.IntegerField(default=0)
    TELEFONE_IMPORTADO  = models.CharField(max_length=100)
    PONTO_REFERENCIA    = models.CharField(max_length=100)
    OBS                = models.CharField(max_length=100)
    ID_IMPORTADO       =  models.IntegerField(default=0)
    NUMERO_IMPORTADO    = models.CharField(max_length=100)
    TOKEN_CELULAR       = models.CharField(max_length=255)
    ID_TABELA          =  models.IntegerField(default=0)
    IPCOOPERATIVA       = models.CharField(max_length=20)
    CHAVE_PIX           = models.CharField(max_length=100)
    TP_CHAVE           = models.CharField(max_length=100)

class Produtos (models.Model):
    ID          =  models.UUIDField(primary_key=True,default=uuid4, editable=False)
    NM_PRODUTO    = models.CharField(max_length=100)
    DESC_PRODUTO    = models.CharField(max_length=600)
    TARIFA_P_METRO  = models.FloatField()
    KM_MINIMO      =  models.IntegerField(default=0)
    VR_KM_MINIMO   =  models.FloatField()
    STATUS          = models.CharField(max_length=1, default="0")
    ID_EMPRESA      =  models.IntegerField(default=0)
    ATIVO_APP      = models.CharField(max_length=1, default="0")

class FormaPgto (models.Model):
    ID    =  models.UUIDField(primary_key=True,default=uuid4, editable=False)
    DESCRICAO   = models.CharField(max_length=100)
    STATUS      = models.CharField(max_length=1, default="0")
    ID_EMPRESA   =  models.IntegerField(default=0)

class Motoboys(models.Model):
    ID   =  models.UUIDField(primary_key=True,default=uuid4, editable=False)
    NOME    = models.CharField(max_length=255)
    CELULAR  = models.CharField(max_length=20)
    TOKEN = models.CharField(max_length=255)
    ONLINE = models.CharField(max_length=1, default="0")