from django.db import models
from uuid import uuid4

# Create your models here.
class Books(models.Model):
    id_book = models.UUIDField(primary_key=True,default=uuid4, editable=False)
    title = models.CharField(max_length=255)
    author = models.CharField(max_length=255)
    release_year = models.IntegerField()
    state = models.CharField(max_length=50)
    pages = models.IntegerField()
    publishing_company = models.CharField(max_length=255)
    create_at = models.DateField(auto_now_add=True)

class Empresa(models.Model):
    EMP_ID   =            models.UUIDField(primary_key=True,default=uuid4, editable=False)
    EMP_FANTASIA =         models.CharField(max_length=255)
    EMP_RAZAOSOCIAL  =     models.CharField(max_length=255)
    EMP_NOMEREDUZIDO   =   models.CharField(max_length=255)
    EMP_PESSOA    =        models.CharField(max_length=1)
    EMP_CPF      =         models.CharField(max_length=11)
    EMP_CNPJ     =         models.CharField(max_length=18)
    EMP_FONES       =       models.CharField(max_length=50)
    EMP_CONTATO     =       models.CharField(max_length=50)
    EMP_SITUACAO    =       models.CharField(max_length=1)
    EMP_OBSERVACAO   =      models.CharField(max_length=255)
    EMP_USUCAD     =        models.CharField(max_length=15)
    EMP_DATCAD     =        models.DateTimeField()
    EMP_USUMOD     =       models.CharField(max_length=15)
    EMP_DATMOD     =       models.DateTimeField()
    EMP_ATIVA       =       models.CharField(max_length=1)
    EMP_API_GOOGLE   =      models.CharField(max_length=255)
    EM_API_URL_BASE   =     models.CharField(max_length=255)
    EMP_API_PAGSEGURO   =  models.CharField(max_length=255)
    EMP_API_URL_BASE    =  models.CharField(max_length=255)
    EMP_VR_KM       =      models.FloatField()
    LIMITE_FIXO    =       models.IntegerField()
    STATUS         =       models.IntegerField()
    VR_LIMITE_FIXO   =       models.FloatField()
    EM_CEP          =      models.CharField(max_length=255)
    EMP_ENDERECO    =      models.CharField(max_length=255),
    EMP_BAIRRO      =      models.CharField(max_length=255)
    EMP_COMPLEMENTO   =     models.CharField(max_length=255)
    EMP_EMAIL         =    models.CharField(max_length=255)
    EMP_NUMERO    =         models.IntegerField()
    EMP_UF            =     models.CharField(max_length=2)
    EMP_CIDADE         =   models.CharField(max_length=255)
    EMP_TELEFONE        =   models.CharField(max_length=255)
    EMP_CELULAR         =   models.CharField(max_length=255)
    EMP_DT_FUNDACAO     =   models.DateField()
    EMP_INC_MUNICIPAL   =   models.CharField(max_length=255)
    EMP_INC_ESTADUAL   =   models.CharField(max_length=255)
    API_KEY_G          =   models.CharField(max_length=255)
    API_CNPJ           =   models.CharField(max_length=255)
    API_CEP            =   models.CharField(max_length=255)
    CHAVE_PIX          =   models.CharField(max_length=255)
    API_WATS               =models.CharField(max_length=255)
    API_WATS_BASE          =models.CharField(max_length=255)
    DIA_DE_FECHAMENTO =   models.IntegerField()
    INICIO_ATIVIDADES     = models.TimeField()
    FIM_ATIVIDADES    =    models.TimeField()
    URLGOOGLE         =    models.CharField(max_length=255)
    COD_PROJ_GOOGLE   =     models.CharField(max_length=255)
    API_GOOGLE         =    models.CharField(max_length=255)
    IMPRIMIR        =       models.IntegerField()
    IP_IMPRESSORA_TERMICA  = models.CharField(max_length=255)
    NM_IMPRESSORA          = models.CharField(max_length=255)

