# Generated by Django 4.2.2 on 2023-06-26 02:47

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Empresa',
            fields=[
                ('EMP_ID', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('EMP_FANTASIA', models.CharField(max_length=255)),
                ('EMP_RAZAOSOCIAL', models.CharField(max_length=255)),
                ('EMP_NOMEREDUZIDO', models.CharField(max_length=255)),
                ('EMP_PESSOA', models.CharField(max_length=1)),
                ('EMP_CPF', models.CharField(max_length=11)),
                ('EMP_CNPJ', models.CharField(max_length=18)),
                ('EMP_FONES', models.CharField(max_length=50)),
                ('EMP_CONTATO', models.CharField(max_length=50)),
                ('EMP_SITUACAO', models.CharField(max_length=1)),
                ('EMP_OBSERVACAO', models.CharField(max_length=255)),
                ('EMP_USUCAD', models.CharField(max_length=15)),
                ('EMP_DATCAD', models.DateTimeField()),
                ('EMP_USUMOD', models.CharField(max_length=15)),
                ('EMP_DATMOD', models.DateTimeField()),
                ('EMP_ATIVA', models.CharField(max_length=1)),
                ('EMP_API_GOOGLE', models.CharField(max_length=255)),
                ('EM_API_URL_BASE', models.CharField(max_length=255)),
                ('EMP_API_PAGSEGURO', models.CharField(max_length=255)),
                ('EMP_API_URL_BASE', models.CharField(max_length=255)),
                ('EMP_VR_KM', models.FloatField()),
                ('LIMITE_FIXO', models.IntegerField()),
                ('STATUS', models.IntegerField()),
                ('VR_LIMITE_FIXO', models.FloatField()),
                ('EM_CEP', models.CharField(max_length=255)),
                ('EMP_BAIRRO', models.CharField(max_length=255)),
                ('EMP_COMPLEMENTO', models.CharField(max_length=255)),
                ('EMP_EMAIL', models.CharField(max_length=255)),
                ('EMP_NUMERO', models.IntegerField()),
                ('EMP_UF', models.CharField(max_length=2)),
                ('EMP_CIDADE', models.CharField(max_length=255)),
                ('EMP_TELEFONE', models.CharField(max_length=255)),
                ('EMP_CELULAR', models.CharField(max_length=255)),
                ('EMP_DT_FUNDACAO', models.DateField()),
                ('EMP_INC_MUNICIPAL', models.CharField(max_length=255)),
                ('EMP_INC_ESTADUAL', models.CharField(max_length=255)),
                ('API_KEY_G', models.CharField(max_length=255)),
                ('API_CNPJ', models.CharField(max_length=255)),
                ('API_CEP', models.CharField(max_length=255)),
                ('CHAVE_PIX', models.CharField(max_length=255)),
                ('API_WATS', models.CharField(max_length=255)),
                ('API_WATS_BASE', models.CharField(max_length=255)),
                ('DIA_DE_FECHAMENTO', models.IntegerField()),
                ('INICIO_ATIVIDADES', models.TimeField()),
                ('FIM_ATIVIDADES', models.TimeField()),
                ('URLGOOGLE', models.CharField(max_length=255)),
                ('COD_PROJ_GOOGLE', models.CharField(max_length=255)),
                ('API_GOOGLE', models.CharField(max_length=255)),
                ('IMPRIMIR', models.IntegerField()),
                ('IP_IMPRESSORA_TERMICA', models.CharField(max_length=255)),
                ('NM_IMPRESSORA', models.CharField(max_length=255)),
            ],
        ),
    ]
