# Generated by Django 4.2.2 on 2023-06-26 03:09

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0002_empresa'),
    ]

    operations = [
        migrations.CreateModel(
            name='Entregas',
            fields=[
                ('ID', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('ID_TIPO_PRODUTO', models.IntegerField(default=3)),
                ('ID_PESSOA', models.IntegerField(default=0)),
                ('ID_MOTOQUEIRO', models.IntegerField(default=0)),
                ('DT_CADASTRO', models.DateTimeField(auto_now_add=True)),
                ('DT_SAIDA', models.DateField()),
                ('DT_ENTREGA', models.DateTimeField(auto_now_add=True)),
                ('ENDERECO_RETIRADA', models.CharField(max_length=600)),
                ('ENDERECO_ENTREGA', models.CharField(max_length=600)),
                ('DESCRICAO', models.CharField(max_length=600)),
                ('DISTANCIA', models.IntegerField()),
                ('DISTANCIA_TXT', models.CharField(max_length=30)),
                ('VR_CALCULADO', models.FloatField()),
                ('VR_POR_METRO', models.FloatField()),
                ('STATUS', models.CharField(max_length=1)),
                ('ID_FORMA_PGTO', models.IntegerField()),
                ('ID_EMPRESA', models.IntegerField()),
                ('ID_USUARIO_ENCERRAMENTO', models.IntegerField()),
                ('ID_USUARIO_INCLUSAO', models.IntegerField()),
                ('COD_TRANSACAO', models.CharField(max_length=20)),
                ('BAIRRO_ENTREGA', models.CharField(max_length=255)),
                ('TRANSACAO_GUID', models.CharField(max_length=38)),
                ('ENDERECO_CLIENTE', models.CharField(max_length=600)),
                ('ANOTACAO', models.CharField(max_length=600)),
                ('ID_USUARIO_ENCAMINHAMENTO', models.IntegerField(default=0)),
                ('TRANSFERIDO', models.IntegerField(default=0)),
            ],
        ),
    ]
