# Generated by Django 4.2.2 on 2023-06-26 18:49

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0003_entregas'),
    ]

    operations = [
        migrations.CreateModel(
            name='Clientes',
            fields=[
                ('IDPESSOA', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('NOME', models.CharField(max_length=255)),
                ('EMAIL', models.CharField(max_length=255)),
                ('CPF', models.CharField(max_length=20)),
                ('CELULAR', models.CharField(max_length=20)),
                ('LATITUDE', models.CharField(max_length=20)),
                ('LONGITUDE', models.CharField(max_length=20)),
                ('ONLINE', models.IntegerField(default=0)),
                ('TOKEN', models.CharField(max_length=255)),
                ('SENHA', models.CharField(max_length=10)),
                ('STATUS', models.CharField(max_length=1)),
                ('TP_PESSOA', models.CharField(default='C', max_length=1)),
                ('DT_TIME_ONLINE', models.DateTimeField(auto_now_add=True)),
                ('ENDERECO', models.CharField(max_length=100)),
                ('BAIRRO', models.CharField(max_length=100)),
                ('NUMERO', models.IntegerField(default=0)),
                ('COMPLEMENTO', models.CharField(max_length=100)),
                ('CEP', models.CharField(max_length=9)),
                ('ESTADO', models.CharField(max_length=100)),
                ('CIDADE', models.CharField(max_length=100)),
                ('TP_CPF_CNPJ', models.IntegerField(default=0)),
                ('TEM_CONTRATO', models.IntegerField(default=0)),
                ('ID_EMPRESA', models.IntegerField(default=0)),
                ('ID_USUARIO', models.IntegerField(default=0)),
                ('IDMOTOQUEIRO', models.IntegerField(default=0)),
                ('TELEFONE_IMPORTADO', models.CharField(max_length=100)),
                ('PONTO_REFERENCIA', models.CharField(max_length=100)),
                ('OBS', models.CharField(max_length=100)),
                ('ID_IMPORTADO', models.IntegerField(default=0)),
                ('NUMERO_IMPORTADO', models.CharField(max_length=100)),
                ('TOKEN_CELULAR', models.CharField(max_length=255)),
                ('ID_TABELA', models.IntegerField(default=0)),
                ('IPCOOPERATIVA', models.CharField(max_length=20)),
                ('CHAVE_PIX', models.CharField(max_length=100)),
                ('TP_CHAVE', models.CharField(max_length=100)),
            ],
        ),
    ]
