# Generated by Django 4.2.2 on 2023-06-26 19:53

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0004_clientes'),
    ]

    operations = [
        migrations.CreateModel(
            name='Produtos',
            fields=[
                ('ID', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('NM_PRODUTO', models.CharField(max_length=100)),
                ('DESC_PRODUTO', models.CharField(max_length=600)),
                ('TARIFA_P_METRO', models.FloatField()),
                ('KM_MINIMO', models.IntegerField(default=0)),
                ('VR_KM_MINIMO', models.FloatField()),
                ('STATUS', models.CharField(default='0', max_length=1)),
                ('ID_EMPRESA', models.IntegerField(default=0)),
                ('ATIVO_APP', models.CharField(default='0', max_length=1)),
            ],
        ),
    ]
