# Generated by Django 4.2.2 on 2023-06-27 02:52

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0006_formapgto'),
    ]

    operations = [
        migrations.CreateModel(
            name='Motoboys',
            fields=[
                ('ID', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('NOME', models.CharField(max_length=255)),
                ('CELULAR', models.CharField(max_length=20)),
                ('TOKEN', models.CharField(max_length=255)),
                ('ONLINE', models.CharField(default='0', max_length=1)),
            ],
        ),
    ]
