# Generated by Django 4.2.2 on 2023-07-10 01:36

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("books", "0008_question_choice"),
    ]

    operations = [
        migrations.AddField(
            model_name="entregas",
            name="NM_CLIENTE",
            field=models.CharField(default="Não informado", max_length=255),
        ),
        migrations.AlterField(
            model_name="entregas",
            name="COD_TRANSACAO",
            field=models.CharField(default=0, max_length=20),
        ),
        migrations.AlterField(
            model_name="entregas",
            name="DISTANCIA",
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name="entregas",
            name="ID_EMPRESA",
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name="entregas",
            name="ID_FORMA_PGTO",
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name="entregas",
            name="ID_USUARIO_ENCERRAMENTO",
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name="entregas",
            name="ID_USUARIO_INCLUSAO",
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name="entregas",
            name="STATUS",
            field=models.CharField(default="P", max_length=1),
        ),
        migrations.AlterField(
            model_name="entregas",
            name="VR_CALCULADO",
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name="entregas",
            name="VR_POR_METRO",
            field=models.FloatField(default=0),
        ),
    ]
