# Generated by Django 4.2.2 on 2023-07-10 01:54

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("books", "0009_entregas_nm_cliente_alter_entregas_cod_transacao_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="entregas",
            name="ANOTACAO",
            field=models.CharField(default="Não informado", max_length=600),
        ),
        migrations.AlterField(
            model_name="entregas",
            name="BAIRRO_ENTREGA",
            field=models.CharField(default="Não informado", max_length=255),
        ),
        migrations.AlterField(
            model_name="entregas",
            name="DT_CADASTRO",
            field=models.DateTimeField(auto_created=True),
        ),
        migrations.AlterField(
            model_name="entregas",
            name="DT_SAIDA",
            field=models.DateField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name="entregas",
            name="ENDERECO_CLIENTE",
            field=models.CharField(default="Não informado", max_length=600),
        ),
        migrations.AlterField(
            model_name="entregas",
            name="TRANSACAO_GUID",
            field=models.CharField(default="Não informado", max_length=38),
        ),
    ]
