# Generated by Django 4.2.2 on 2023-07-10 02:01

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("books", "0010_alter_entregas_anotacao_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="entregas",
            name="DT_CADASTRO",
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
