# Generated by Django 4.2.2 on 2023-07-11 20:40

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("books", "0011_alter_entregas_dt_cadastro"),
    ]

    operations = [
        migrations.AlterField(
            model_name="clientes",
            name="BAIRRO",
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name="clientes",
            name="CELULAR",
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name="clientes",
            name="CEP",
            field=models.CharField(max_length=9, null=True),
        ),
        migrations.AlterField(
            model_name="clientes",
            name="CHAVE_PIX",
            field=models.CharField(default="Nome", max_length=100),
        ),
        migrations.AlterField(
            model_name="clientes",
            name="CIDADE",
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name="clientes",
            name="COMPLEMENTO",
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name="clientes",
            name="CPF",
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name="clientes",
            name="EMAIL",
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name="clientes",
            name="ENDERECO",
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name="clientes",
            name="ESTADO",
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name="clientes",
            name="IDMOTOQUEIRO",
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name="clientes",
            name="ID_EMPRESA",
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name="clientes",
            name="ID_IMPORTADO",
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name="clientes",
            name="ID_USUARIO",
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name="clientes",
            name="IPCOOPERATIVA",
            field=models.CharField(default="Nome", max_length=20),
        ),
        migrations.AlterField(
            model_name="clientes",
            name="LATITUDE",
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name="clientes",
            name="LONGITUDE",
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name="clientes",
            name="NUMERO",
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name="clientes",
            name="NUMERO_IMPORTADO",
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name="clientes",
            name="OBS",
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name="clientes",
            name="PONTO_REFERENCIA",
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name="clientes",
            name="SENHA",
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name="clientes",
            name="STATUS",
            field=models.CharField(max_length=1, null=True),
        ),
        migrations.AlterField(
            model_name="clientes",
            name="TELEFONE_IMPORTADO",
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name="clientes",
            name="TEM_CONTRATO",
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name="clientes",
            name="TOKEN",
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name="clientes",
            name="TOKEN_CELULAR",
            field=models.CharField(default="", max_length=255),
        ),
        migrations.AlterField(
            model_name="clientes",
            name="TP_CHAVE",
            field=models.CharField(default="Nome", max_length=100),
        ),
        migrations.AlterField(
            model_name="clientes",
            name="TP_CPF_CNPJ",
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name="entregas",
            name="DESCRICAO",
            field=models.CharField(max_length=600, null=True),
        ),
        migrations.AlterField(
            model_name="entregas",
            name="DISTANCIA",
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name="entregas",
            name="DISTANCIA_TXT",
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name="entregas",
            name="ENDERECO_ENTREGA",
            field=models.CharField(max_length=600, null=True),
        ),
        migrations.AlterField(
            model_name="entregas",
            name="ENDERECO_RETIRADA",
            field=models.CharField(max_length=600, null=True),
        ),
        migrations.AlterField(
            model_name="entregas",
            name="ID_EMPRESA",
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name="entregas",
            name="ID_FORMA_PGTO",
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name="entregas",
            name="ID_MOTOQUEIRO",
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name="entregas",
            name="ID_PESSOA",
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name="entregas",
            name="ID_TIPO_PRODUTO",
            field=models.IntegerField(default=3, null=True),
        ),
        migrations.AlterField(
            model_name="entregas",
            name="ID_USUARIO_ENCAMINHAMENTO",
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name="entregas",
            name="ID_USUARIO_ENCERRAMENTO",
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name="entregas",
            name="ID_USUARIO_INCLUSAO",
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name="entregas",
            name="TRANSFERIDO",
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name="entregas",
            name="VR_CALCULADO",
            field=models.FloatField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name="entregas",
            name="VR_POR_METRO",
            field=models.FloatField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name="produtos",
            name="TARIFA_P_METRO",
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name="produtos",
            name="VR_KM_MINIMO",
            field=models.FloatField(default=0),
        ),
    ]
