# Generated by Django 4.2.2 on 2023-07-11 21:04

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("books", "0012_alter_clientes_bairro_alter_clientes_celular_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="empresa",
            name="EMP_ENDERECO",
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name="clientes",
            name="CHAVE_PIX",
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name="clientes",
            name="IPCOOPERATIVA",
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name="clientes",
            name="TP_CHAVE",
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name="empresa",
            name="API_CEP",
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name="empresa",
            name="API_CNPJ",
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name="empresa",
            name="API_GOOGLE",
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name="empresa",
            name="API_KEY_G",
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name="empresa",
            name="API_WATS",
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name="empresa",
            name="API_WATS_BASE",
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name="empresa",
            name="CHAVE_PIX",
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name="empresa",
            name="COD_PROJ_GOOGLE",
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name="empresa",
            name="DIA_DE_FECHAMENTO",
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name="empresa",
            name="EMP_API_GOOGLE",
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name="empresa",
            name="EMP_API_PAGSEGURO",
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name="empresa",
            name="EMP_API_URL_BASE",
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name="empresa",
            name="EMP_ATIVA",
            field=models.CharField(max_length=1, null=True),
        ),
        migrations.AlterField(
            model_name="empresa",
            name="EMP_BAIRRO",
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name="empresa",
            name="EMP_CELULAR",
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name="empresa",
            name="EMP_CIDADE",
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name="empresa",
            name="EMP_CNPJ",
            field=models.CharField(max_length=18, null=True),
        ),
        migrations.AlterField(
            model_name="empresa",
            name="EMP_COMPLEMENTO",
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name="empresa",
            name="EMP_CONTATO",
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name="empresa",
            name="EMP_CPF",
            field=models.CharField(max_length=11, null=True),
        ),
        migrations.AlterField(
            model_name="empresa",
            name="EMP_DATCAD",
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name="empresa",
            name="EMP_DATMOD",
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name="empresa",
            name="EMP_DT_FUNDACAO",
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name="empresa",
            name="EMP_EMAIL",
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name="empresa",
            name="EMP_FONES",
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name="empresa",
            name="EMP_INC_ESTADUAL",
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name="empresa",
            name="EMP_INC_MUNICIPAL",
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name="empresa",
            name="EMP_NUMERO",
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name="empresa",
            name="EMP_OBSERVACAO",
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name="empresa",
            name="EMP_PESSOA",
            field=models.CharField(max_length=1, null=True),
        ),
        migrations.AlterField(
            model_name="empresa",
            name="EMP_SITUACAO",
            field=models.CharField(max_length=1, null=True),
        ),
        migrations.AlterField(
            model_name="empresa",
            name="EMP_TELEFONE",
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name="empresa",
            name="EMP_UF",
            field=models.CharField(max_length=2, null=True),
        ),
        migrations.AlterField(
            model_name="empresa",
            name="EMP_USUCAD",
            field=models.CharField(max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name="empresa",
            name="EMP_USUMOD",
            field=models.CharField(max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name="empresa",
            name="EMP_VR_KM",
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name="empresa",
            name="EM_API_URL_BASE",
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name="empresa",
            name="EM_CEP",
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name="empresa",
            name="FIM_ATIVIDADES",
            field=models.TimeField(null=True),
        ),
        migrations.AlterField(
            model_name="empresa",
            name="IMPRIMIR",
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name="empresa",
            name="INICIO_ATIVIDADES",
            field=models.TimeField(null=True),
        ),
        migrations.AlterField(
            model_name="empresa",
            name="IP_IMPRESSORA_TERMICA",
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name="empresa",
            name="LIMITE_FIXO",
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name="empresa",
            name="NM_IMPRESSORA",
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name="empresa",
            name="STATUS",
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name="empresa",
            name="URLGOOGLE",
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name="empresa",
            name="VR_LIMITE_FIXO",
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name="produtos",
            name="DESC_PRODUTO",
            field=models.CharField(max_length=600, null=True),
        ),
    ]
