# Generated by Django 4.2.2 on 2023-07-13 21:44

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("books", "0013_empresa_emp_endereco_alter_clientes_chave_pix_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="entregas",
            name="NM_FORMA_PGTO",
            field=models.CharField(default="Não selecionado", max_length=30),
        ),
        migrations.AddField(
            model_name="entregas",
            name="NM_MOTOQUEIRO",
            field=models.CharField(default="Não selecionado", max_length=100),
        ),
        migrations.AddField(
            model_name="entregas",
            name="NM_PESSOA",
            field=models.CharField(default="Não selecionado", max_length=200),
        ),
        migrations.AddField(
            model_name="entregas",
            name="NM_PRODUTO",
            field=models.CharField(default="Não selecionado", max_length=30),
        ),
        migrations.AddField(
            model_name="entregas",
            name="NM_USUARIO_ENCERRAMENTO",
            field=models.CharField(default="Não informado", max_length=200),
        ),
        migrations.AlterField(
            model_name="entregas",
            name="DT_ENTREGA",
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name="entregas",
            name="DT_SAIDA",
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name="entregas",
            name="ID_EMPRESA",
            field=models.UUIDField(null=True),
        ),
        migrations.AlterField(
            model_name="entregas",
            name="ID_FORMA_PGTO",
            field=models.UUIDField(null=True),
        ),
        migrations.AlterField(
            model_name="entregas",
            name="ID_MOTOQUEIRO",
            field=models.UUIDField(null=True),
        ),
        migrations.AlterField(
            model_name="entregas",
            name="ID_PESSOA",
            field=models.UUIDField(null=True),
        ),
        migrations.AlterField(
            model_name="entregas",
            name="ID_TIPO_PRODUTO",
            field=models.UUIDField(null=True),
        ),
        migrations.AlterField(
            model_name="entregas",
            name="ID_USUARIO_ENCAMINHAMENTO",
            field=models.UUIDField(null=True),
        ),
        migrations.AlterField(
            model_name="entregas",
            name="ID_USUARIO_ENCERRAMENTO",
            field=models.UUIDField(null=True),
        ),
        migrations.AlterField(
            model_name="entregas",
            name="ID_USUARIO_INCLUSAO",
            field=models.UUIDField(null=True),
        ),
        migrations.AlterField(
            model_name="produtos",
            name="ID_EMPRESA",
            field=models.UUIDField(null=True),
        ),
    ]
