# Generated by Django 4.2.2 on 2023-07-13 22:18

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("books", "0014_entregas_nm_forma_pgto_entregas_nm_motoqueiro_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="entregas",
            name="ID_EMPRESA",
            field=models.CharField(default=0, max_length=38),
        ),
        migrations.AlterField(
            model_name="entregas",
            name="ID_FORMA_PGTO",
            field=models.CharField(default=0, max_length=38),
        ),
        migrations.AlterField(
            model_name="entregas",
            name="ID_MOTOQUEIRO",
            field=models.CharField(default=0, max_length=38),
        ),
        migrations.AlterField(
            model_name="entregas",
            name="ID_PESSOA",
            field=models.CharField(default=0, max_length=38),
        ),
        migrations.AlterField(
            model_name="entregas",
            name="ID_TIPO_PRODUTO",
            field=models.CharField(default=0, max_length=38),
        ),
        migrations.AlterField(
            model_name="entregas",
            name="ID_USUARIO_ENCAMINHAMENTO",
            field=models.CharField(default=0, max_length=38),
        ),
        migrations.AlterField(
            model_name="entregas",
            name="ID_USUARIO_ENCERRAMENTO",
            field=models.CharField(default=0, max_length=38),
        ),
        migrations.AlterField(
            model_name="entregas",
            name="ID_USUARIO_INCLUSAO",
            field=models.CharField(default=0, max_length=38),
        ),
        migrations.AlterField(
            model_name="entregas",
            name="STATUS",
            field=models.CharField(default="S", max_length=1),
        ),
        migrations.AlterField(
            model_name="formapgto",
            name="ID_EMPRESA",
            field=models.CharField(default=0, max_length=38),
        ),
        migrations.AlterField(
            model_name="produtos",
            name="ID_EMPRESA",
            field=models.CharField(default=0, max_length=38),
        ),
    ]
