# Generated by Django 4.2.2 on 2023-07-15 01:59

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("books", "0015_alter_entregas_id_empresa_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="motoboys",
            name="FOTO",
            field=models.ImageField(null=True, upload_to=""),
        ),
    ]
