# Generated by Django 4.2.2 on 2023-08-01 03:08

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("books", "0016_motoboys_foto"),
    ]

    operations = [
        migrations.AlterField(
            model_name="clientes",
            name="ID_TABELA",
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name="clientes",
            name="ONLINE",
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name="clientes",
            name="TOKEN_CELULAR",
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name="clientes",
            name="TP_PESSOA",
            field=models.CharField(max_length=1, null=True),
        ),
    ]
