# Generated by Django 4.2.2 on 2023-08-01 12:05

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("books", "0017_alter_clientes_id_tabela_alter_clientes_online_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="clientes",
            name="TOKEN",
            field=models.CharField(default="Não informado", max_length=255),
        ),
    ]
