# Generated by Django 4.2.2 on 2023-08-01 12:09

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("books", "0019_alter_clientes_senha_alter_clientes_status"),
    ]

    operations = [
        migrations.AlterField(
            model_name="clientes",
            name="TP_PESSOA",
            field=models.CharField(default="Não informado", max_length=1),
        ),
    ]
