# Generated by Django 4.2.2 on 2023-08-01 12:10

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("books", "0020_alter_clientes_tp_pessoa"),
    ]

    operations = [
        migrations.AlterField(
            model_name="clientes",
            name="BAIRRO",
            field=models.CharField(default="Não informado", max_length=100),
        ),
        migrations.AlterField(
            model_name="clientes",
            name="ENDERECO",
            field=models.CharField(default="Não informado", max_length=100),
        ),
    ]
