# Generated by Django 4.2.2 on 2023-08-02 11:51

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("books", "0021_alter_clientes_bairro_alter_clientes_endereco"),
    ]

    operations = [
        migrations.AddField(
            model_name="entregas",
            name="DATA_DE_CADASTRO",
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AddField(
            model_name="entregas",
            name="DATA_DE_ENTREGA",
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name="clientes",
            name="CIDADE",
            field=models.CharField(default="Não informado", max_length=100),
        ),
        migrations.AlterField(
            model_name="clientes",
            name="COMPLEMENTO",
            field=models.CharField(default="Não informado", max_length=100),
        ),
        migrations.AlterField(
            model_name="clientes",
            name="ESTADO",
            field=models.CharField(default="Não informado", max_length=100),
        ),
        migrations.AlterField(
            model_name="clientes",
            name="STATUS",
            field=models.CharField(default="0", max_length=1),
        ),
        migrations.AlterField(
            model_name="clientes",
            name="TELEFONE_IMPORTADO",
            field=models.CharField(default="Não informado", max_length=100),
        ),
        migrations.AlterField(
            model_name="clientes",
            name="TP_PESSOA",
            field=models.CharField(default="C", max_length=1),
        ),
    ]
