# Generated by Django 5.0.1 on 2024-01-14 01:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0022_entregas_data_de_cadastro_entregas_data_de_entrega_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='produtos',
            name='ID',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
