# Generated by Django 5.0.1 on 2024-01-14 01:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0023_alter_produtos_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='produtos',
            name='ID',
            field=models.AutoField(editable=False, primary_key=True, serialize=False),
        ),
    ]
