# Generated by Django 5.0.1 on 2024-01-14 01:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0024_alter_produtos_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='clientes',
            name='CK_ATIVO',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='clientes',
            name='NR_CELULAR2',
            field=models.BigIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='clientes',
            name='ONLINE_2',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='clientes',
            name='IDPESSOA',
            field=models.AutoField(editable=False, primary_key=True, serialize=False),
        ),
    ]
