# Generated by Django 5.0.1 on 2024-01-14 02:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0025_clientes_ck_ativo_clientes_nr_celular2_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clientes',
            name='CK_ATIVO',
            field=models.BooleanField(null=True),
        ),
        migrations.AlterField(
            model_name='clientes',
            name='ONLINE_2',
            field=models.BooleanField(null=True),
        ),
    ]
