# Generated by Django 5.0.1 on 2024-01-14 02:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0027_alter_clientes_bairro_alter_clientes_cidade_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clientes',
            name='NR_CELULAR2',
            field=models.BigIntegerField(null=True),
        ),
    ]
