# Generated by Django 5.0.1 on 2024-01-14 02:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0028_alter_clientes_nr_celular2'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clientes',
            name='NUMERO',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='clientes',
            name='ONLINE',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
