# Generated by Django 5.0.1 on 2024-01-14 21:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0029_alter_clientes_numero_alter_clientes_online'),
    ]

    operations = [
        migrations.AlterField(
            model_name='formapgto',
            name='ID',
            field=models.AutoField(editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='motoboys',
            name='ID',
            field=models.AutoField(editable=False, primary_key=True, serialize=False),
        ),
    ]
