# Generated by Django 5.0.1 on 2024-01-15 02:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0031_meuslocais'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entregas',
            name='ID',
            field=models.AutoField(editable=False, primary_key=True, serialize=False),
        ),
    ]
