# Generated by Django 5.0.1 on 2024-01-15 02:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0032_alter_entregas_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entregas',
            name='DATA_DE_CADASTRO',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='entregas',
            name='DATA_DE_ENTREGA',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='entregas',
            name='DT_CADASTRO',
            field=models.DateField(auto_now_add=True),
        ),
    ]
