# Generated by Django 5.0.1 on 2024-01-15 11:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0033_alter_entregas_data_de_cadastro_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clientes',
            name='CELULAR',
            field=models.CharField(max_length=20, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='clientes',
            name='CPF',
            field=models.CharField(max_length=20, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='motoboys',
            name='CELULAR',
            field=models.CharField(max_length=20, unique=True),
        ),
    ]
