# Generated by Django 5.0.1 on 2024-01-18 13:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0034_alter_clientes_celular_alter_clientes_cpf_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='motoboys',
            name='ID_USER',
            field=models.IntegerField(default=0),
        ),
    ]
