# Generated by Django 5.0.1 on 2024-01-24 02:48

import books.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0035_motoboys_id_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='motoboys',
            name='FOTO',
            field=models.ImageField(blank=True, null=True, upload_to=books.models.upload_image_motoboy),
        ),
    ]
