# Generated by Django 5.0.1 on 2024-01-24 13:56

import books.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0037_rename_id_motoboys_id_motoboy'),
    ]

    operations = [
        migrations.AddField(
            model_name='motoboys',
            name='arquivo',
            field=models.FileField(blank=True, null=True, upload_to=books.models.upload_image_motoboy),
        ),
    ]
