# Generated by Django 5.0.1 on 2024-02-12 20:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0039_remove_motoboys_arquivo_clientes_foto'),
    ]

    operations = [
        migrations.AddField(
            model_name='entregas',
            name='URL_IMAGEM',
            field=models.URLField(blank=True, max_length=255, null=True),
        ),
    ]
