# Generated by Django 5.0.1 on 2024-02-19 12:11

import books.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0040_entregas_url_imagem'),
    ]

    operations = [
        migrations.AddField(
            model_name='entregas',
            name='IMG_ASSINATURA',
            field=models.ImageField(blank=True, null=True, upload_to=books.models.upload_image_assinatura),
        ),
        migrations.AddField(
            model_name='entregas',
            name='NM_ATENDENTE',
            field=models.CharField(default='Não informado', max_length=200),
        ),
        migrations.AlterField(
            model_name='entregas',
            name='STATUS',
            field=models.CharField(default='0', max_length=1),
        ),
    ]
