# Generated by Django 5.0.1 on 2024-05-24 01:44

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("books", "0041_entregas_img_assinatura_entregas_nm_atendente_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="entregas",
            name="IMG_ASS_BASE64",
            field=models.BinaryField(null=True),
        ),
    ]
