# Generated by Django 5.0.1 on 2024-05-24 01:48

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("books", "0042_entregas_img_ass_base64"),
    ]

    operations = [
        migrations.AlterField(
            model_name="entregas",
            name="IMG_ASS_BASE64",
            field=models.TextField(null=True),
        ),
    ]
