# Generated by Django 5.0.1 on 2024-05-31 13:03

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("books", "0043_alter_entregas_img_ass_base64"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="entregas",
            name="IMG_ASS_BASE64",
        ),
    ]
